name: WakaTime Readme Stats

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_EDITORS: true
          SHOW_LANGUAGE: true
          SHOW_LINES_OF_CODE: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_PROFILE_VIEWS: true
